### PR TITLE
Adding SRE France - Summer Camp 2022

### PR DESCRIPTION
**Pull request by zwindler**
* Adding SRE France - Summer Camp 2022
* Moving July to archive
* Expiring some CFPs

### CODE REVIEW

**Comment by zwindler** [comment]
Woops, I missed https://github.com/scraly/developers-conferences-agenda/pull/225

Sorry 😬

**Comment by scraly** [comment]
Can you fix it? ^^

**Comment by zwindler** [comment]
It's fixed :smiley:

**Comment by scraly** [comment]
Merkiiiii

**Pull request merged**
