### PR TITLE
Fix end date computation in parser.py (fixes #319)

### LINKED ISSUE #319: Invalid dates generated by `parser.py`
Invalid dates are generated by `parser.py` for the following conference : `27-01: [Elastic{ON}](https://www.elastic.co/elasticon/conf/2018/sf) - USA (San Francisco)` (in https://github.com/scraly/developers-conferences-agenda/blob/main/archives/2018.md) :
```json
{"name": "Elastic{ON}", "date": [1519689600, 1517443201], "hyperlink": "https://www.elastic.co/elasticon/conf/2018/sf", "location": "USA (San Francisco)", "misc": ""}
```

The start timestamp is correct (`1519689600` == `2018-02-27`), but the end timestamp is wrong (`1517443201` == `2018-02-01`). It should have been `2018-03-01`.

### PR DESCRIPTION
**Pull request by marcwrobel**
Diff between old json and new json (timezone = Europe/Paris) :

```json
--- oldf.json	2023-01-05 22:00:58.083757282 +0100
+++ newf.json	2023-01-05 22:01:03.043911122 +0100
@@ -853,7 +853,7 @@
     "name": "Elastic{ON}",
     "date": [
       1519686000,
-      1517439601
+      1519858801
     ],
     "hyperlink": "https://www.elastic.co/elasticon/conf/2018/sf",
     "location": "USA (San Francisco)",
@@ -1363,7 +1363,7 @@
     "name": "Gopher Con Iceland",
     "date": [
       1527717600,
-      1525298401
+      1527976801
     ],
     "hyperlink": "https://gophercon.is/",
     "location": "Iceland",
@@ -1603,7 +1603,7 @@
     "name": "La nuit du Hack",
     "date": [
       1530309600,
-      1527804001
+      1530396001
     ],
     "hyperlink": "https://www.nuitduhack.com/fr",
     "location": "France (Paris)",
@@ -2253,7 +2253,7 @@
     "name": "DockerCon 2019",
     "date": [
       1556488800,
-      1554156001
+      1556748001
     ],
     "hyperlink": "https://dockercon19.smarteventscloud.com/portal/newreg.ww",
     "location": "USA (San Francisco)",
@@ -2263,7 +2263,7 @@
     "name": "Rails Conf",
     "date": [
       1556575200,
-      1554156001
+      1556748001
     ],
     "hyperlink": "https://railsconf.com/",
     "location": "USA (Minneapolis)",
@@ -2473,7 +2473,7 @@
     "name": "GopherCon Europe",
     "date": [
       1559167200,
-      1556661601
+      1559340001
     ],
     "hyperlink": "https://www.gophercon.es",
     "location": "Tenerife",
@@ -4883,7 +4883,7 @@
     "name": "web3 Con",
     "date": [
       1646002800,
-      1644102001
+      1646521201
     ],
     "hyperlink": "https://www.web3con.dev/",
     "location": "Online",
@@ -5303,7 +5303,7 @@
     "name": "PyCon US",
     "date": [
       1651010400,
-      1648936801
+      1651528801
     ],
     "hyperlink": "https://us.pycon.org/2022/",
     "location": "Salt Lake City (USA)",
@@ -5773,7 +5773,7 @@
     "name": "Craft Conference",
     "date": [
       1653948000,
-      1651528801
+      1654207201
     ],
     "hyperlink": "https://craft-conf.com/",
     "location": "Budapest (Hungary) ",
@@ -6173,7 +6173,7 @@
     "name": "Hack in Paris",
     "date": [
       1656280800,
-      1654034401
+      1656626401
     ],
     "hyperlink": "https://hackinparis.com/",
     "location": "Paris (France) ",
@@ -6203,7 +6203,7 @@
     "name": "BreizhCamp",
     "date": [
       1656453600,
-      1654034401
+      1656626401
     ],
     "hyperlink": "https://www.breizhcamp.org/",
     "location": "Rennes (France) ",
@@ -6213,7 +6213,7 @@
     "name": "Sunny Tech",
     "date": [
       1656540000,
-      1654034401
+      1656626401
     ],
     "hyperlink": "https://sunny-tech.io/",
     "location": "Montpellier (France) ",
@@ -6223,7 +6223,7 @@
     "name": "Agi'Lille 2022",
     "date": [
       1656540000,
-      1654034401
+      1656626401
     ],
     "hyperlink": "https://agilille.fr/",
     "location": "Lille (France) ",
```

### CODE REVIEW

**Comment by marcwrobel** [comment]
I am not sure, but there may be an issue with the use of unix timestamps (which are sensitive to the timezone/UTC offset). Using two ISO 8601 dates would have been safer.

**Review by HanzCEO — APPROVED** [review]

**Comment by HanzCEO** [comment]
It's been two weeks.
The changes LGTM.

**Comment by HanzCEO** [comment]
> I am not sure, but there may be an issue in the site with the use of unix timestamps (which are sensitive to the timezone/UTC offset). Current timestamps are in UTC, not sure if https://developers.events/ is assuming UTC too.

This is something tricky. In order to fix this, this repository needs a guideline (seek #290).
I would like to propose a writing convention that would enable us to give additional information to the parser program. Like the `<meta>` tag in HTML that could be used to fix this timezone issue.

Currently, the parser program also stores `misc` data that mostly contains "markdown badges".
This `misc` field is an opportunity for the convention.

**Comment by marcwrobel** [comment]
Hi @HanzCEO, thanks for taking the time to review this.

> This is something tricky. In order to fix this, this repository needs a guideline (seek #290).
> I would like to propose a writing convention that would enable us to give additional information to the parser program. Like the `<meta>` tag in HTML that could be used to fix this timezone issue.

I do not think additional information are necessary : we already have the date and the location, which should be sufficient. My concern (which may or may not be an issue) was about the fact that the date is stored in the JSON file (and in the javascript code) using a timestamp, which implies a specific time. It would have been better if ISO 8601 dates (i.e. `yyyy-mm-dd` strings) were used.

But I agree, additional convention could be useful for making things simpler to use (at the risk of making things more complex for the contributors).

**Comment by HanzCEO** [comment]
Location data are not persistent, some items omit this. A pinch of
conferences are also held online. Which, in this repository, marked as
"Online" and no specific location hint. Hence, I think timezone metadata is
needed.

About the ISO 8601, it is generally a nice idea for short term usage. Also
good for direct readability.

I'm thinking of future contributor who wants to improve the accuracy of our
event calendar by adding specific-hour detail. I think the ISO convention
is good for display, not for processing.

**Comment by HanzCEO** [comment]
This PR LGTM and ready to merge @scraly

**Comment by scraly** [comment]
Thanks for this PR :)

**Pull request merged**
