### PR TITLE
Add DevSecCon 2024

### PR DESCRIPTION
**Pull request by rdegges**
Adding the DevSecCon 2024 event and CFP to the repo per the contributing instructions.

### CODE REVIEW

**Comment by scraly** [comment]
Thx :)

**Comment by rdegges** [comment]
Quick question =) I noticed that on the live site it shows the date as one day earlier than was listed in the README. Any idea why that might be?

**Comment by scraly** [comment]
The event will take place the 8 and 9 of October and in the website I see the event for the good date
image

Can you explain me the problem?
Thanks :)

**Comment by rdegges** [comment]
Hmm, when I view it, I see this:

Screenshot 2024-07-26 at 11 04 47 AM

Maybe it's just a timezone thing? No biggie.

**Pull request merged**
