### PR TITLE
Add Devfest Lille 2023 and CFP dates

### PR DESCRIPTION
**Pull request by wiblu59**
Hello, we would like to add the dates for Devfest Lille 2023 🎉

### CODE REVIEW

**Comment by geromegrignon** [comment]
Hi @wiblu59 is the CFP opened the 3rd (from conference hall link) or the 10th (data here)?

**Comment by wiblu59** [comment]
Hi @geromegrignon, thanks for checking! It will indeed open on the 10th. We will fix this on Conference Hall 👀

**Comment by wiblu59** [comment]
It should indeed open on Jan, 3th. I messed up the dates. all good now ✅

**Comment by scraly** [comment]
Thanks to you two :)

**Pull request merged**
