### PR TITLE
Add Scroll to Top button to improve page navigation.

### PR DESCRIPTION
**Pull request by iBerserker89**
Hi, i made a scroll-to-top button to improve navigation. This is my first contribution to a real open source project and hope it is good enough.

### CODE REVIEW

**Comment by scraly** [comment]
Hi,
thanks for the PR :) 

My remark:
The components are in a folder:
image

It should be good to keep the coherence and have all the components inside its folder.

**Comment by iBerserker89** [comment]
Sorry for the lack of attention. I just refactored the code.

**Review by scraly — CHANGES_REQUESTED** [review]
Thanks.
After analyzed it deeply, I found two last things to change to keep consistency :).

After that I will approve and merge your PR.

**Comment by iBerserker89** [comment]
Just made the suggested changes. Hope it is all good now.

**Review by scraly — APPROVED** [review]

**Comment by scraly** [comment]
Thanks! :-)

**Pull request merged**
