### PR TITLE
Add KCD Australia

### PR DESCRIPTION
**Pull request by agardnerIT**

### CODE REVIEW

**Comment by scraly** [comment]
The first link should be the link of the event, the website with all the informations
not the cfp link
can you update the PR with the kcd australia 2024 website link? :) 

thx

**Review by scraly — CHANGES_REQUESTED** [review]
Need to replace the first link to a website link

**Comment by agardnerIT** [comment]
Done. Hopefully that's OK :)

**Comment by scraly** [comment]
Thanks it's OK :) 

If a page is created like this one for 2023: https://community.cncf.io/events/details/cncf-kcd-australia-presents-kubernetes-community-day-australia-2023/

Don't hesitate to create a PR

**Pull request merged**
