### PR TITLE
feat: New Filter UI (No new list view commits)

### PR DESCRIPTION
**Pull request by HanzCEO**
Cherry picked

### CODE REVIEW

**Comment by scraly** [comment]
It's OK for me, just one thing.

I tested on small screen and it's a little buggy in "list" view:

image

The 3 icons at the right are not displayed, only the first.

**Comment by HanzCEO** [comment]
It should fix it

**Comment by scraly** [comment]
Thanks, it sounds better :) 
Can you rebase in order to pull the latest events? :) 
And then I will merge it.

**Comment by scraly** [comment]
There is one behavior that is strange to me.
In the current version, I can change the filter and watch the events listed, and change the filter again:
image

In your version, I can't see all the events listed:
image

The events are truncated. Is it possible to have the same behavior?

**Comment by HanzCEO** [comment]
@scraly, I will stand on my ground to keep my changes because of performance reason. There is a lot of people who doesn't run their browser with smooth graphics card or display. However, it is possible if someone were to structurally change the Filter component placement. Right now, I just see it as a technical debt for not placing the filter in the right place.

**Comment by scraly** [comment]
OK that's ok for me :)

**Pull request merged**
