### PR TITLE
Adding a new List View to list events.

### PR DESCRIPTION
**Pull request by jespino**
Probably there is some polishing doable around making the list looks nicer, but it is working, and I don't really know how to make it look nicer because there is no much data. Here is a screenshot of this working:

imagen

### CODE REVIEW

**Comment by scraly** [comment]
Cool, I love it!

I found a bug:
- click on March
- scroll up, click on the list button
- I see january instead of march
image

**Comment by jespino** [comment]
from my POV the calendar view allows you to see things per month and per day, the list view shows the whole year always. We can add filters in the list view based on that. Something like filter by month, but for me, by default I expect the list view to show everything (in the year).

**Comment by scraly** [comment]
I understand.

I think it might be useful to add the "month" in the listing view.
The goal is to have the listing (a list) of events, like in the README view :).
image

By the way, I see the events in the "cards" not in a list on Firefox:
image

**Comment by jespino** [comment]
Does it looks like more to what you want?
imagen

**Comment by jespino** [comment]
Added the changes to show the list in the format of the README

**Comment by scraly** [comment]
I like to see the events ordered and listed by months.
It's good for the readability. :-) 

Now, is it possible to have the list a little more "pretty" :-)

For example, a look and feel like this:
image

(with a lighter gray)
But with the date of the event in first (like in the readme)

Thanks!

**Comment by scraly** [comment]
By the way, I really love to list only opended CFP! :-) 

image

**Comment by jespino** [comment]
New iteration :)

And yes, I agree, I was missing that view too. I really want to have at a glance all the open CFP to submit something.

**Comment by scraly** [comment]
After reflection, I would like a mix between 1 and 2 🙂

The listing in "README" style but with the light gray box:
image

and with the CFP/closed captions labels... in a line below

I think it will be light, readable and perfect 🥰

**Comment by jespino** [comment]
What do you think now?

imagen

**Comment by scraly** [comment]
Top! :)

**Comment by scraly** [comment]
I really like this new feature. It allows users to have only the list, not the calendar view.
Easy :)

Thanks

**Pull request merged**
