### PR TITLE
Add Open Source Festival 2023 (Oscafest)

### PR DESCRIPTION
**Pull request by geoffreylgv**

### CODE REVIEW

**Comment by geoffreylgv** [comment]
Added Two events, for May 2023 :
- The Bitcoin Conference in Miami, FL (USA)
- The Microsoft Build in Seattle, WA (USA)

**Comment by geoffreylgv** [comment]
New commit/push : 
- Removed The bitcoin conference 2023 in Miami,
- updated with the upcoming bitcoin conference 2024 in Nashville, and 
- added Africa bitcoin conference 2023 in Accra.

**Comment by scraly** [comment]
thanks :)

**Comment by geoffreylgv** [comment]
It's my pleasure 🥰

**Pull request merged**
