### PR TITLE
Add Lyon Craft conference

### PR DESCRIPTION
**Pull request by DamnClin**
Adding a new French conference

### CODE REVIEW

**Comment by scraly** [comment]
Lyon Craft will be the 4th of April or March? :)

**Comment by DamnClin** [comment]
> Lyon Craft will be the 4th of April or March? :)

April... Totally failed the line, fixed

**Comment by scraly** [comment]
Thanks :)

**Comment by DamnClin** [comment]
> Thanks :)

Thank you for pointing that out!

**Pull request merged**
