### PR TITLE
fix : cfp date parser + format validation

### PR DESCRIPTION
**Pull request by Damien-VS**
the CFP dates are off, because the date format is all over the place.

added a event entry validation with hints to help with correcting the various parsing problems that might occur

### CODE REVIEW

**Comment by Damien-VS** [comment]
Comment to explain :
## CFP dates are all over the place
 fixed the parser to accept multiple date formats

## Added validator
 on build, the validation will execute and identify ligne with a format that can pose problems with the parser.
it is not blocking (lots a archives are off format), just informing.
Exemple from this PR build logs: 
image

## Fix event calendar date acceptation
the events were shown 1 day after their end date in the calendar, because the end date is set at midnight.
fixed an "<=" into "<" to follow the old calendar behaviour

**Comment by scraly** [comment]
Thx! ♥️♥️♥️

**Comment by scraly** [comment]
Thanks!
I love the idea of the validator :-).

About the fix, I tested with one event in december "DevTernity" that will take place the 7 & 8, I see the event if I click on the 8 but not if I click on the 7:
image

image

**Comment by scraly** [comment]
I approve and I will put the bug in an issue ;-)

**Pull request merged**
